// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: leveldb_ycsb.proto

#include "leveldb_ycsb.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace ycsbleveldb {
class ReadMDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ReadM>
      _instance;
} _ReadM_default_instance_;
class ScanMDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ScanM>
      _instance;
} _ScanM_default_instance_;
class UpdateMDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<UpdateM>
      _instance;
} _UpdateM_default_instance_;
class InsertMDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<InsertM>
      _instance;
} _InsertM_default_instance_;
class DeleteMDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<DeleteM>
      _instance;
} _DeleteM_default_instance_;
class ResultDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<Result>
      _instance;
} _Result_default_instance_;
class ReadResultDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ReadResult>
      _instance;
} _ReadResult_default_instance_;
}  // namespace ycsbleveldb
namespace protobuf_leveldb_5fycsb_2eproto {
static void InitDefaultsReadM() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::ycsbleveldb::_ReadM_default_instance_;
    new (ptr) ::ycsbleveldb::ReadM();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::ycsbleveldb::ReadM::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_ReadM =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsReadM}, {}};

static void InitDefaultsScanM() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::ycsbleveldb::_ScanM_default_instance_;
    new (ptr) ::ycsbleveldb::ScanM();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::ycsbleveldb::ScanM::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_ScanM =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsScanM}, {}};

static void InitDefaultsUpdateM() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::ycsbleveldb::_UpdateM_default_instance_;
    new (ptr) ::ycsbleveldb::UpdateM();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::ycsbleveldb::UpdateM::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_UpdateM =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsUpdateM}, {}};

static void InitDefaultsInsertM() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::ycsbleveldb::_InsertM_default_instance_;
    new (ptr) ::ycsbleveldb::InsertM();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::ycsbleveldb::InsertM::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_InsertM =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsInsertM}, {}};

static void InitDefaultsDeleteM() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::ycsbleveldb::_DeleteM_default_instance_;
    new (ptr) ::ycsbleveldb::DeleteM();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::ycsbleveldb::DeleteM::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_DeleteM =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsDeleteM}, {}};

static void InitDefaultsResult() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::ycsbleveldb::_Result_default_instance_;
    new (ptr) ::ycsbleveldb::Result();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::ycsbleveldb::Result::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_Result =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsResult}, {}};

static void InitDefaultsReadResult() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::ycsbleveldb::_ReadResult_default_instance_;
    new (ptr) ::ycsbleveldb::ReadResult();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::ycsbleveldb::ReadResult::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_ReadResult =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsReadResult}, {}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_ReadM.base);
  ::google::protobuf::internal::InitSCC(&scc_info_ScanM.base);
  ::google::protobuf::internal::InitSCC(&scc_info_UpdateM.base);
  ::google::protobuf::internal::InitSCC(&scc_info_InsertM.base);
  ::google::protobuf::internal::InitSCC(&scc_info_DeleteM.base);
  ::google::protobuf::internal::InitSCC(&scc_info_Result.base);
  ::google::protobuf::internal::InitSCC(&scc_info_ReadResult.base);
}

::google::protobuf::Metadata file_level_metadata[7];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ycsbleveldb::ReadM, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ycsbleveldb::ReadM, table_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ycsbleveldb::ReadM, key_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ycsbleveldb::ScanM, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ycsbleveldb::ScanM, table_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ycsbleveldb::ScanM, startkey_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ycsbleveldb::ScanM, recordcount_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ycsbleveldb::ScanM, field_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ycsbleveldb::UpdateM, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ycsbleveldb::UpdateM, table_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ycsbleveldb::UpdateM, key_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ycsbleveldb::UpdateM, values_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ycsbleveldb::InsertM, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ycsbleveldb::InsertM, table_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ycsbleveldb::InsertM, key_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ycsbleveldb::InsertM, values_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ycsbleveldb::DeleteM, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ycsbleveldb::DeleteM, table_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ycsbleveldb::DeleteM, key_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ycsbleveldb::Result, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ycsbleveldb::Result, result_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ycsbleveldb::ReadResult, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ycsbleveldb::ReadResult, output_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ycsbleveldb::ReadResult, result_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::ycsbleveldb::ReadM)},
  { 7, -1, sizeof(::ycsbleveldb::ScanM)},
  { 16, -1, sizeof(::ycsbleveldb::UpdateM)},
  { 24, -1, sizeof(::ycsbleveldb::InsertM)},
  { 32, -1, sizeof(::ycsbleveldb::DeleteM)},
  { 39, -1, sizeof(::ycsbleveldb::Result)},
  { 45, -1, sizeof(::ycsbleveldb::ReadResult)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::ycsbleveldb::_ReadM_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::ycsbleveldb::_ScanM_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::ycsbleveldb::_UpdateM_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::ycsbleveldb::_InsertM_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::ycsbleveldb::_DeleteM_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::ycsbleveldb::_Result_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::ycsbleveldb::_ReadResult_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "leveldb_ycsb.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 7);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\022leveldb_ycsb.proto\022\013ycsbleveldb\"#\n\005Rea"
      "dM\022\r\n\005table\030\001 \001(\t\022\013\n\003key\030\002 \001(\t\"L\n\005ScanM\022"
      "\r\n\005table\030\001 \001(\t\022\020\n\010startkey\030\002 \001(\t\022\023\n\013reco"
      "rdcount\030\003 \001(\005\022\r\n\005field\030\004 \001(\t\"5\n\007UpdateM\022"
      "\r\n\005table\030\001 \001(\t\022\013\n\003key\030\002 \001(\t\022\016\n\006values\030\003 "
      "\001(\t\"5\n\007InsertM\022\r\n\005table\030\001 \001(\t\022\013\n\003key\030\002 \001"
      "(\t\022\016\n\006values\030\003 \001(\t\"%\n\007DeleteM\022\r\n\005table\030\001"
      " \001(\t\022\013\n\003key\030\002 \001(\t\"\030\n\006Result\022\016\n\006result\030\001 "
      "\001(\005\",\n\nReadResult\022\016\n\006output\030\001 \001(\t\022\016\n\006res"
      "ult\030\002 \001(\0052\235\002\n\007LevelDB\0225\n\004Read\022\022.ycsbleve"
      "ldb.ReadM\032\027.ycsbleveldb.ReadResult\"\000\0225\n\004"
      "Scan\022\022.ycsbleveldb.ScanM\032\027.ycsbleveldb.R"
      "eadResult\"\000\0225\n\006Update\022\024.ycsbleveldb.Upda"
      "teM\032\023.ycsbleveldb.Result\"\000\0225\n\006Insert\022\024.y"
      "csbleveldb.InsertM\032\023.ycsbleveldb.Result\""
      "\000\0226\n\007Ldelete\022\024.ycsbleveldb.DeleteM\032\023.ycs"
      "bleveldb.Result\"\000B/\n\031com.yahoo.ycsb.db.l"
      "eveldbB\nYCSBLeveDBP\001\242\002\003LDBb\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 714);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "leveldb_ycsb.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_leveldb_5fycsb_2eproto
namespace ycsbleveldb {

// ===================================================================

void ReadM::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ReadM::kTableFieldNumber;
const int ReadM::kKeyFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ReadM::ReadM()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_leveldb_5fycsb_2eproto::scc_info_ReadM.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:ycsbleveldb.ReadM)
}
ReadM::ReadM(const ReadM& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  table_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.table().size() > 0) {
    table_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.table_);
  }
  key_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.key().size() > 0) {
    key_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.key_);
  }
  // @@protoc_insertion_point(copy_constructor:ycsbleveldb.ReadM)
}

void ReadM::SharedCtor() {
  table_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  key_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

ReadM::~ReadM() {
  // @@protoc_insertion_point(destructor:ycsbleveldb.ReadM)
  SharedDtor();
}

void ReadM::SharedDtor() {
  table_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  key_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void ReadM::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* ReadM::descriptor() {
  ::protobuf_leveldb_5fycsb_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_leveldb_5fycsb_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ReadM& ReadM::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_leveldb_5fycsb_2eproto::scc_info_ReadM.base);
  return *internal_default_instance();
}


void ReadM::Clear() {
// @@protoc_insertion_point(message_clear_start:ycsbleveldb.ReadM)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  table_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  key_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

bool ReadM::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:ycsbleveldb.ReadM)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string table = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_table()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->table().data(), static_cast<int>(this->table().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "ycsbleveldb.ReadM.table"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string key = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_key()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->key().data(), static_cast<int>(this->key().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "ycsbleveldb.ReadM.key"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:ycsbleveldb.ReadM)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:ycsbleveldb.ReadM)
  return false;
#undef DO_
}

void ReadM::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:ycsbleveldb.ReadM)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string table = 1;
  if (this->table().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->table().data(), static_cast<int>(this->table().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "ycsbleveldb.ReadM.table");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->table(), output);
  }

  // string key = 2;
  if (this->key().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->key().data(), static_cast<int>(this->key().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "ycsbleveldb.ReadM.key");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->key(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:ycsbleveldb.ReadM)
}

::google::protobuf::uint8* ReadM::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:ycsbleveldb.ReadM)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string table = 1;
  if (this->table().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->table().data(), static_cast<int>(this->table().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "ycsbleveldb.ReadM.table");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->table(), target);
  }

  // string key = 2;
  if (this->key().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->key().data(), static_cast<int>(this->key().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "ycsbleveldb.ReadM.key");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->key(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ycsbleveldb.ReadM)
  return target;
}

size_t ReadM::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ycsbleveldb.ReadM)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string table = 1;
  if (this->table().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->table());
  }

  // string key = 2;
  if (this->key().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->key());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ReadM::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:ycsbleveldb.ReadM)
  GOOGLE_DCHECK_NE(&from, this);
  const ReadM* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ReadM>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:ycsbleveldb.ReadM)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:ycsbleveldb.ReadM)
    MergeFrom(*source);
  }
}

void ReadM::MergeFrom(const ReadM& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:ycsbleveldb.ReadM)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.table().size() > 0) {

    table_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.table_);
  }
  if (from.key().size() > 0) {

    key_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.key_);
  }
}

void ReadM::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:ycsbleveldb.ReadM)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ReadM::CopyFrom(const ReadM& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ycsbleveldb.ReadM)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ReadM::IsInitialized() const {
  return true;
}

void ReadM::Swap(ReadM* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ReadM::InternalSwap(ReadM* other) {
  using std::swap;
  table_.Swap(&other->table_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  key_.Swap(&other->key_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata ReadM::GetMetadata() const {
  protobuf_leveldb_5fycsb_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_leveldb_5fycsb_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void ScanM::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ScanM::kTableFieldNumber;
const int ScanM::kStartkeyFieldNumber;
const int ScanM::kRecordcountFieldNumber;
const int ScanM::kFieldFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ScanM::ScanM()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_leveldb_5fycsb_2eproto::scc_info_ScanM.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:ycsbleveldb.ScanM)
}
ScanM::ScanM(const ScanM& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  table_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.table().size() > 0) {
    table_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.table_);
  }
  startkey_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.startkey().size() > 0) {
    startkey_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.startkey_);
  }
  field_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.field().size() > 0) {
    field_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.field_);
  }
  recordcount_ = from.recordcount_;
  // @@protoc_insertion_point(copy_constructor:ycsbleveldb.ScanM)
}

void ScanM::SharedCtor() {
  table_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  startkey_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  field_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  recordcount_ = 0;
}

ScanM::~ScanM() {
  // @@protoc_insertion_point(destructor:ycsbleveldb.ScanM)
  SharedDtor();
}

void ScanM::SharedDtor() {
  table_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  startkey_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  field_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void ScanM::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* ScanM::descriptor() {
  ::protobuf_leveldb_5fycsb_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_leveldb_5fycsb_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ScanM& ScanM::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_leveldb_5fycsb_2eproto::scc_info_ScanM.base);
  return *internal_default_instance();
}


void ScanM::Clear() {
// @@protoc_insertion_point(message_clear_start:ycsbleveldb.ScanM)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  table_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  startkey_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  field_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  recordcount_ = 0;
  _internal_metadata_.Clear();
}

bool ScanM::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:ycsbleveldb.ScanM)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string table = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_table()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->table().data(), static_cast<int>(this->table().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "ycsbleveldb.ScanM.table"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string startkey = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_startkey()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->startkey().data(), static_cast<int>(this->startkey().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "ycsbleveldb.ScanM.startkey"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 recordcount = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &recordcount_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string field = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u /* 34 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_field()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->field().data(), static_cast<int>(this->field().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "ycsbleveldb.ScanM.field"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:ycsbleveldb.ScanM)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:ycsbleveldb.ScanM)
  return false;
#undef DO_
}

void ScanM::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:ycsbleveldb.ScanM)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string table = 1;
  if (this->table().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->table().data(), static_cast<int>(this->table().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "ycsbleveldb.ScanM.table");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->table(), output);
  }

  // string startkey = 2;
  if (this->startkey().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->startkey().data(), static_cast<int>(this->startkey().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "ycsbleveldb.ScanM.startkey");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->startkey(), output);
  }

  // int32 recordcount = 3;
  if (this->recordcount() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->recordcount(), output);
  }

  // string field = 4;
  if (this->field().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->field().data(), static_cast<int>(this->field().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "ycsbleveldb.ScanM.field");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      4, this->field(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:ycsbleveldb.ScanM)
}

::google::protobuf::uint8* ScanM::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:ycsbleveldb.ScanM)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string table = 1;
  if (this->table().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->table().data(), static_cast<int>(this->table().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "ycsbleveldb.ScanM.table");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->table(), target);
  }

  // string startkey = 2;
  if (this->startkey().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->startkey().data(), static_cast<int>(this->startkey().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "ycsbleveldb.ScanM.startkey");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->startkey(), target);
  }

  // int32 recordcount = 3;
  if (this->recordcount() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->recordcount(), target);
  }

  // string field = 4;
  if (this->field().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->field().data(), static_cast<int>(this->field().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "ycsbleveldb.ScanM.field");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        4, this->field(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ycsbleveldb.ScanM)
  return target;
}

size_t ScanM::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ycsbleveldb.ScanM)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string table = 1;
  if (this->table().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->table());
  }

  // string startkey = 2;
  if (this->startkey().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->startkey());
  }

  // string field = 4;
  if (this->field().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->field());
  }

  // int32 recordcount = 3;
  if (this->recordcount() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->recordcount());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ScanM::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:ycsbleveldb.ScanM)
  GOOGLE_DCHECK_NE(&from, this);
  const ScanM* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ScanM>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:ycsbleveldb.ScanM)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:ycsbleveldb.ScanM)
    MergeFrom(*source);
  }
}

void ScanM::MergeFrom(const ScanM& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:ycsbleveldb.ScanM)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.table().size() > 0) {

    table_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.table_);
  }
  if (from.startkey().size() > 0) {

    startkey_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.startkey_);
  }
  if (from.field().size() > 0) {

    field_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.field_);
  }
  if (from.recordcount() != 0) {
    set_recordcount(from.recordcount());
  }
}

void ScanM::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:ycsbleveldb.ScanM)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ScanM::CopyFrom(const ScanM& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ycsbleveldb.ScanM)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ScanM::IsInitialized() const {
  return true;
}

void ScanM::Swap(ScanM* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ScanM::InternalSwap(ScanM* other) {
  using std::swap;
  table_.Swap(&other->table_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  startkey_.Swap(&other->startkey_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  field_.Swap(&other->field_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(recordcount_, other->recordcount_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata ScanM::GetMetadata() const {
  protobuf_leveldb_5fycsb_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_leveldb_5fycsb_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void UpdateM::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int UpdateM::kTableFieldNumber;
const int UpdateM::kKeyFieldNumber;
const int UpdateM::kValuesFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

UpdateM::UpdateM()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_leveldb_5fycsb_2eproto::scc_info_UpdateM.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:ycsbleveldb.UpdateM)
}
UpdateM::UpdateM(const UpdateM& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  table_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.table().size() > 0) {
    table_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.table_);
  }
  key_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.key().size() > 0) {
    key_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.key_);
  }
  values_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.values().size() > 0) {
    values_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.values_);
  }
  // @@protoc_insertion_point(copy_constructor:ycsbleveldb.UpdateM)
}

void UpdateM::SharedCtor() {
  table_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  key_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  values_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

UpdateM::~UpdateM() {
  // @@protoc_insertion_point(destructor:ycsbleveldb.UpdateM)
  SharedDtor();
}

void UpdateM::SharedDtor() {
  table_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  key_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  values_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void UpdateM::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* UpdateM::descriptor() {
  ::protobuf_leveldb_5fycsb_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_leveldb_5fycsb_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const UpdateM& UpdateM::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_leveldb_5fycsb_2eproto::scc_info_UpdateM.base);
  return *internal_default_instance();
}


void UpdateM::Clear() {
// @@protoc_insertion_point(message_clear_start:ycsbleveldb.UpdateM)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  table_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  key_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  values_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

bool UpdateM::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:ycsbleveldb.UpdateM)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string table = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_table()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->table().data(), static_cast<int>(this->table().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "ycsbleveldb.UpdateM.table"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string key = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_key()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->key().data(), static_cast<int>(this->key().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "ycsbleveldb.UpdateM.key"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string values = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_values()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->values().data(), static_cast<int>(this->values().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "ycsbleveldb.UpdateM.values"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:ycsbleveldb.UpdateM)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:ycsbleveldb.UpdateM)
  return false;
#undef DO_
}

void UpdateM::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:ycsbleveldb.UpdateM)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string table = 1;
  if (this->table().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->table().data(), static_cast<int>(this->table().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "ycsbleveldb.UpdateM.table");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->table(), output);
  }

  // string key = 2;
  if (this->key().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->key().data(), static_cast<int>(this->key().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "ycsbleveldb.UpdateM.key");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->key(), output);
  }

  // string values = 3;
  if (this->values().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->values().data(), static_cast<int>(this->values().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "ycsbleveldb.UpdateM.values");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->values(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:ycsbleveldb.UpdateM)
}

::google::protobuf::uint8* UpdateM::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:ycsbleveldb.UpdateM)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string table = 1;
  if (this->table().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->table().data(), static_cast<int>(this->table().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "ycsbleveldb.UpdateM.table");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->table(), target);
  }

  // string key = 2;
  if (this->key().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->key().data(), static_cast<int>(this->key().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "ycsbleveldb.UpdateM.key");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->key(), target);
  }

  // string values = 3;
  if (this->values().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->values().data(), static_cast<int>(this->values().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "ycsbleveldb.UpdateM.values");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->values(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ycsbleveldb.UpdateM)
  return target;
}

size_t UpdateM::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ycsbleveldb.UpdateM)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string table = 1;
  if (this->table().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->table());
  }

  // string key = 2;
  if (this->key().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->key());
  }

  // string values = 3;
  if (this->values().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->values());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void UpdateM::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:ycsbleveldb.UpdateM)
  GOOGLE_DCHECK_NE(&from, this);
  const UpdateM* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const UpdateM>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:ycsbleveldb.UpdateM)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:ycsbleveldb.UpdateM)
    MergeFrom(*source);
  }
}

void UpdateM::MergeFrom(const UpdateM& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:ycsbleveldb.UpdateM)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.table().size() > 0) {

    table_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.table_);
  }
  if (from.key().size() > 0) {

    key_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.key_);
  }
  if (from.values().size() > 0) {

    values_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.values_);
  }
}

void UpdateM::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:ycsbleveldb.UpdateM)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void UpdateM::CopyFrom(const UpdateM& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ycsbleveldb.UpdateM)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool UpdateM::IsInitialized() const {
  return true;
}

void UpdateM::Swap(UpdateM* other) {
  if (other == this) return;
  InternalSwap(other);
}
void UpdateM::InternalSwap(UpdateM* other) {
  using std::swap;
  table_.Swap(&other->table_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  key_.Swap(&other->key_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  values_.Swap(&other->values_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata UpdateM::GetMetadata() const {
  protobuf_leveldb_5fycsb_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_leveldb_5fycsb_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void InsertM::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int InsertM::kTableFieldNumber;
const int InsertM::kKeyFieldNumber;
const int InsertM::kValuesFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

InsertM::InsertM()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_leveldb_5fycsb_2eproto::scc_info_InsertM.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:ycsbleveldb.InsertM)
}
InsertM::InsertM(const InsertM& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  table_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.table().size() > 0) {
    table_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.table_);
  }
  key_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.key().size() > 0) {
    key_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.key_);
  }
  values_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.values().size() > 0) {
    values_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.values_);
  }
  // @@protoc_insertion_point(copy_constructor:ycsbleveldb.InsertM)
}

void InsertM::SharedCtor() {
  table_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  key_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  values_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

InsertM::~InsertM() {
  // @@protoc_insertion_point(destructor:ycsbleveldb.InsertM)
  SharedDtor();
}

void InsertM::SharedDtor() {
  table_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  key_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  values_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void InsertM::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* InsertM::descriptor() {
  ::protobuf_leveldb_5fycsb_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_leveldb_5fycsb_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const InsertM& InsertM::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_leveldb_5fycsb_2eproto::scc_info_InsertM.base);
  return *internal_default_instance();
}


void InsertM::Clear() {
// @@protoc_insertion_point(message_clear_start:ycsbleveldb.InsertM)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  table_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  key_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  values_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

bool InsertM::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:ycsbleveldb.InsertM)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string table = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_table()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->table().data(), static_cast<int>(this->table().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "ycsbleveldb.InsertM.table"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string key = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_key()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->key().data(), static_cast<int>(this->key().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "ycsbleveldb.InsertM.key"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string values = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_values()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->values().data(), static_cast<int>(this->values().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "ycsbleveldb.InsertM.values"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:ycsbleveldb.InsertM)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:ycsbleveldb.InsertM)
  return false;
#undef DO_
}

void InsertM::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:ycsbleveldb.InsertM)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string table = 1;
  if (this->table().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->table().data(), static_cast<int>(this->table().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "ycsbleveldb.InsertM.table");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->table(), output);
  }

  // string key = 2;
  if (this->key().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->key().data(), static_cast<int>(this->key().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "ycsbleveldb.InsertM.key");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->key(), output);
  }

  // string values = 3;
  if (this->values().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->values().data(), static_cast<int>(this->values().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "ycsbleveldb.InsertM.values");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->values(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:ycsbleveldb.InsertM)
}

::google::protobuf::uint8* InsertM::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:ycsbleveldb.InsertM)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string table = 1;
  if (this->table().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->table().data(), static_cast<int>(this->table().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "ycsbleveldb.InsertM.table");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->table(), target);
  }

  // string key = 2;
  if (this->key().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->key().data(), static_cast<int>(this->key().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "ycsbleveldb.InsertM.key");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->key(), target);
  }

  // string values = 3;
  if (this->values().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->values().data(), static_cast<int>(this->values().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "ycsbleveldb.InsertM.values");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->values(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ycsbleveldb.InsertM)
  return target;
}

size_t InsertM::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ycsbleveldb.InsertM)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string table = 1;
  if (this->table().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->table());
  }

  // string key = 2;
  if (this->key().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->key());
  }

  // string values = 3;
  if (this->values().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->values());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void InsertM::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:ycsbleveldb.InsertM)
  GOOGLE_DCHECK_NE(&from, this);
  const InsertM* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const InsertM>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:ycsbleveldb.InsertM)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:ycsbleveldb.InsertM)
    MergeFrom(*source);
  }
}

void InsertM::MergeFrom(const InsertM& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:ycsbleveldb.InsertM)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.table().size() > 0) {

    table_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.table_);
  }
  if (from.key().size() > 0) {

    key_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.key_);
  }
  if (from.values().size() > 0) {

    values_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.values_);
  }
}

void InsertM::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:ycsbleveldb.InsertM)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void InsertM::CopyFrom(const InsertM& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ycsbleveldb.InsertM)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool InsertM::IsInitialized() const {
  return true;
}

void InsertM::Swap(InsertM* other) {
  if (other == this) return;
  InternalSwap(other);
}
void InsertM::InternalSwap(InsertM* other) {
  using std::swap;
  table_.Swap(&other->table_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  key_.Swap(&other->key_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  values_.Swap(&other->values_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata InsertM::GetMetadata() const {
  protobuf_leveldb_5fycsb_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_leveldb_5fycsb_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void DeleteM::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int DeleteM::kTableFieldNumber;
const int DeleteM::kKeyFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

DeleteM::DeleteM()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_leveldb_5fycsb_2eproto::scc_info_DeleteM.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:ycsbleveldb.DeleteM)
}
DeleteM::DeleteM(const DeleteM& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  table_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.table().size() > 0) {
    table_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.table_);
  }
  key_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.key().size() > 0) {
    key_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.key_);
  }
  // @@protoc_insertion_point(copy_constructor:ycsbleveldb.DeleteM)
}

void DeleteM::SharedCtor() {
  table_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  key_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

DeleteM::~DeleteM() {
  // @@protoc_insertion_point(destructor:ycsbleveldb.DeleteM)
  SharedDtor();
}

void DeleteM::SharedDtor() {
  table_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  key_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void DeleteM::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* DeleteM::descriptor() {
  ::protobuf_leveldb_5fycsb_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_leveldb_5fycsb_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const DeleteM& DeleteM::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_leveldb_5fycsb_2eproto::scc_info_DeleteM.base);
  return *internal_default_instance();
}


void DeleteM::Clear() {
// @@protoc_insertion_point(message_clear_start:ycsbleveldb.DeleteM)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  table_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  key_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

bool DeleteM::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:ycsbleveldb.DeleteM)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string table = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_table()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->table().data(), static_cast<int>(this->table().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "ycsbleveldb.DeleteM.table"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string key = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_key()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->key().data(), static_cast<int>(this->key().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "ycsbleveldb.DeleteM.key"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:ycsbleveldb.DeleteM)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:ycsbleveldb.DeleteM)
  return false;
#undef DO_
}

void DeleteM::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:ycsbleveldb.DeleteM)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string table = 1;
  if (this->table().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->table().data(), static_cast<int>(this->table().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "ycsbleveldb.DeleteM.table");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->table(), output);
  }

  // string key = 2;
  if (this->key().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->key().data(), static_cast<int>(this->key().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "ycsbleveldb.DeleteM.key");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->key(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:ycsbleveldb.DeleteM)
}

::google::protobuf::uint8* DeleteM::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:ycsbleveldb.DeleteM)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string table = 1;
  if (this->table().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->table().data(), static_cast<int>(this->table().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "ycsbleveldb.DeleteM.table");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->table(), target);
  }

  // string key = 2;
  if (this->key().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->key().data(), static_cast<int>(this->key().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "ycsbleveldb.DeleteM.key");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->key(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ycsbleveldb.DeleteM)
  return target;
}

size_t DeleteM::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ycsbleveldb.DeleteM)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string table = 1;
  if (this->table().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->table());
  }

  // string key = 2;
  if (this->key().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->key());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void DeleteM::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:ycsbleveldb.DeleteM)
  GOOGLE_DCHECK_NE(&from, this);
  const DeleteM* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const DeleteM>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:ycsbleveldb.DeleteM)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:ycsbleveldb.DeleteM)
    MergeFrom(*source);
  }
}

void DeleteM::MergeFrom(const DeleteM& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:ycsbleveldb.DeleteM)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.table().size() > 0) {

    table_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.table_);
  }
  if (from.key().size() > 0) {

    key_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.key_);
  }
}

void DeleteM::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:ycsbleveldb.DeleteM)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void DeleteM::CopyFrom(const DeleteM& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ycsbleveldb.DeleteM)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DeleteM::IsInitialized() const {
  return true;
}

void DeleteM::Swap(DeleteM* other) {
  if (other == this) return;
  InternalSwap(other);
}
void DeleteM::InternalSwap(DeleteM* other) {
  using std::swap;
  table_.Swap(&other->table_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  key_.Swap(&other->key_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata DeleteM::GetMetadata() const {
  protobuf_leveldb_5fycsb_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_leveldb_5fycsb_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void Result::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Result::kResultFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Result::Result()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_leveldb_5fycsb_2eproto::scc_info_Result.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:ycsbleveldb.Result)
}
Result::Result(const Result& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  result_ = from.result_;
  // @@protoc_insertion_point(copy_constructor:ycsbleveldb.Result)
}

void Result::SharedCtor() {
  result_ = 0;
}

Result::~Result() {
  // @@protoc_insertion_point(destructor:ycsbleveldb.Result)
  SharedDtor();
}

void Result::SharedDtor() {
}

void Result::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* Result::descriptor() {
  ::protobuf_leveldb_5fycsb_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_leveldb_5fycsb_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const Result& Result::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_leveldb_5fycsb_2eproto::scc_info_Result.base);
  return *internal_default_instance();
}


void Result::Clear() {
// @@protoc_insertion_point(message_clear_start:ycsbleveldb.Result)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  result_ = 0;
  _internal_metadata_.Clear();
}

bool Result::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:ycsbleveldb.Result)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 result = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &result_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:ycsbleveldb.Result)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:ycsbleveldb.Result)
  return false;
#undef DO_
}

void Result::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:ycsbleveldb.Result)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 result = 1;
  if (this->result() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->result(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:ycsbleveldb.Result)
}

::google::protobuf::uint8* Result::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:ycsbleveldb.Result)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 result = 1;
  if (this->result() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->result(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ycsbleveldb.Result)
  return target;
}

size_t Result::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ycsbleveldb.Result)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // int32 result = 1;
  if (this->result() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->result());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Result::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:ycsbleveldb.Result)
  GOOGLE_DCHECK_NE(&from, this);
  const Result* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Result>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:ycsbleveldb.Result)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:ycsbleveldb.Result)
    MergeFrom(*source);
  }
}

void Result::MergeFrom(const Result& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:ycsbleveldb.Result)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.result() != 0) {
    set_result(from.result());
  }
}

void Result::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:ycsbleveldb.Result)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Result::CopyFrom(const Result& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ycsbleveldb.Result)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Result::IsInitialized() const {
  return true;
}

void Result::Swap(Result* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Result::InternalSwap(Result* other) {
  using std::swap;
  swap(result_, other->result_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata Result::GetMetadata() const {
  protobuf_leveldb_5fycsb_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_leveldb_5fycsb_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void ReadResult::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ReadResult::kOutputFieldNumber;
const int ReadResult::kResultFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ReadResult::ReadResult()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_leveldb_5fycsb_2eproto::scc_info_ReadResult.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:ycsbleveldb.ReadResult)
}
ReadResult::ReadResult(const ReadResult& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  output_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.output().size() > 0) {
    output_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.output_);
  }
  result_ = from.result_;
  // @@protoc_insertion_point(copy_constructor:ycsbleveldb.ReadResult)
}

void ReadResult::SharedCtor() {
  output_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  result_ = 0;
}

ReadResult::~ReadResult() {
  // @@protoc_insertion_point(destructor:ycsbleveldb.ReadResult)
  SharedDtor();
}

void ReadResult::SharedDtor() {
  output_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void ReadResult::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* ReadResult::descriptor() {
  ::protobuf_leveldb_5fycsb_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_leveldb_5fycsb_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ReadResult& ReadResult::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_leveldb_5fycsb_2eproto::scc_info_ReadResult.base);
  return *internal_default_instance();
}


void ReadResult::Clear() {
// @@protoc_insertion_point(message_clear_start:ycsbleveldb.ReadResult)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  output_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  result_ = 0;
  _internal_metadata_.Clear();
}

bool ReadResult::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:ycsbleveldb.ReadResult)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string output = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_output()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->output().data(), static_cast<int>(this->output().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "ycsbleveldb.ReadResult.output"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 result = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &result_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:ycsbleveldb.ReadResult)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:ycsbleveldb.ReadResult)
  return false;
#undef DO_
}

void ReadResult::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:ycsbleveldb.ReadResult)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string output = 1;
  if (this->output().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->output().data(), static_cast<int>(this->output().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "ycsbleveldb.ReadResult.output");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->output(), output);
  }

  // int32 result = 2;
  if (this->result() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->result(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:ycsbleveldb.ReadResult)
}

::google::protobuf::uint8* ReadResult::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:ycsbleveldb.ReadResult)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string output = 1;
  if (this->output().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->output().data(), static_cast<int>(this->output().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "ycsbleveldb.ReadResult.output");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->output(), target);
  }

  // int32 result = 2;
  if (this->result() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->result(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ycsbleveldb.ReadResult)
  return target;
}

size_t ReadResult::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ycsbleveldb.ReadResult)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string output = 1;
  if (this->output().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->output());
  }

  // int32 result = 2;
  if (this->result() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->result());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ReadResult::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:ycsbleveldb.ReadResult)
  GOOGLE_DCHECK_NE(&from, this);
  const ReadResult* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ReadResult>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:ycsbleveldb.ReadResult)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:ycsbleveldb.ReadResult)
    MergeFrom(*source);
  }
}

void ReadResult::MergeFrom(const ReadResult& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:ycsbleveldb.ReadResult)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.output().size() > 0) {

    output_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.output_);
  }
  if (from.result() != 0) {
    set_result(from.result());
  }
}

void ReadResult::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:ycsbleveldb.ReadResult)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ReadResult::CopyFrom(const ReadResult& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ycsbleveldb.ReadResult)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ReadResult::IsInitialized() const {
  return true;
}

void ReadResult::Swap(ReadResult* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ReadResult::InternalSwap(ReadResult* other) {
  using std::swap;
  output_.Swap(&other->output_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(result_, other->result_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata ReadResult::GetMetadata() const {
  protobuf_leveldb_5fycsb_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_leveldb_5fycsb_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace ycsbleveldb
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::ycsbleveldb::ReadM* Arena::CreateMaybeMessage< ::ycsbleveldb::ReadM >(Arena* arena) {
  return Arena::CreateInternal< ::ycsbleveldb::ReadM >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::ycsbleveldb::ScanM* Arena::CreateMaybeMessage< ::ycsbleveldb::ScanM >(Arena* arena) {
  return Arena::CreateInternal< ::ycsbleveldb::ScanM >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::ycsbleveldb::UpdateM* Arena::CreateMaybeMessage< ::ycsbleveldb::UpdateM >(Arena* arena) {
  return Arena::CreateInternal< ::ycsbleveldb::UpdateM >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::ycsbleveldb::InsertM* Arena::CreateMaybeMessage< ::ycsbleveldb::InsertM >(Arena* arena) {
  return Arena::CreateInternal< ::ycsbleveldb::InsertM >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::ycsbleveldb::DeleteM* Arena::CreateMaybeMessage< ::ycsbleveldb::DeleteM >(Arena* arena) {
  return Arena::CreateInternal< ::ycsbleveldb::DeleteM >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::ycsbleveldb::Result* Arena::CreateMaybeMessage< ::ycsbleveldb::Result >(Arena* arena) {
  return Arena::CreateInternal< ::ycsbleveldb::Result >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::ycsbleveldb::ReadResult* Arena::CreateMaybeMessage< ::ycsbleveldb::ReadResult >(Arena* arena) {
  return Arena::CreateInternal< ::ycsbleveldb::ReadResult >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
